"""缠论知识图谱数据定义 - 55个概念节点 + 85条关系"""

CONCEPTS = [
    # ===== 基础原理 =====
    {"id": "走势终完美", "category": "基础原理", "importance": 36,
     "description": "缠论的第一基本原理：任何级别的任何走势类型，都必然会完成（终结），走势可以被唯一分解为上涨、下跌、盘整的连接。这是一个不证自明的公理，也是整个缠论理论体系的基础。",
     "aliases": ["终完美", "走势完结"]},
    {"id": "走势必完美", "category": "基础原理", "importance": 32,
     "description": "缠论定理：走势的唯一分解定理。任何走势都可以被唯一分解。递归函数：f1(a0)=a1（基础情况），f2(an)=an+1（递归情况）。走势必完美是走势终完美的操作化。",
     "aliases": ["必完美", "唯一分解"]},
    {"id": "自同构性", "category": "基础原理", "importance": 30,
     "description": "缠论的核心支点之一：自同构性结构的绝对复制性。不同级别的走势具有相同的结构，分型、中枢、趋势在所有级别的定义都相同。这是区间套方法的理论基础。",
     "aliases": ["自同构", "结构复制"]},
    {"id": "完全分类", "category": "基础原理", "importance": 28,
     "description": "缠论操作哲学：走势类型只有上涨、下跌、盘整三种，对所有可能的走势进行完全分类，针对每种情况制定对应的应对策略。不预测，只应对。",
     "aliases": ["完全分类体系", "分类"]},

    # ===== 核心概念 =====
    {"id": "中枢", "category": "核心概念", "importance": 40,
     "description": "缠论最核心的定义。某级别走势类型中，被至少三个连续的次级别走势类型所重叠的部分。中枢是走势的基本单位，是多空博弈均衡的价格区间（纳什均衡）。中枢有上沿ZG和下沿ZD。",
     "aliases": ["价格中枢", "中枢区间", "ZG", "ZD"]},
    {"id": "背驰", "category": "核心概念", "importance": 36,
     "description": "价格创新高/低但动能减弱的现象。背驰是买卖点的必然来源，任一背驰都必然制造某级别的买卖点。判断方式：MACD面积对比、黄白线高低、成交量等。包括趋势背驰和盘整背驰两种。",
     "aliases": ["趋势背驰", "盘整背驰", "背离"]},
    {"id": "次级别", "category": "核心概念", "importance": 38,
     "description": "缠论的本源与核心逻辑。次级别是高级别的构成元素，是中枢定义的核心（中枢=三段次级别走势类型的重叠）。次级别是精确识别的起点、转折判断的关键、操作精度的基础、风险管理的依据、级别转换的桥梁。",
     "aliases": ["次级别走势", "下级"]},
    {"id": "走势类型", "category": "核心概念", "importance": 34,
     "description": "缠论的基本分析对象，分为上涨（两个以上同向上涨中枢）、下跌（两个以上同向下跌中枢）、盘整（只有一个中枢）三种类型。走势类型由次级别走势类型构成。",
     "aliases": ["走势", "趋势类型"]},
    {"id": "级别", "category": "核心概念", "importance": 32,
     "description": "缠论的核心维度。常用级别：1分钟、5分钟、30分钟、日线、周线等。高级别由次级别构成（Level(n) = f(Level(n-1))），级别间关系是递归生成的。不同级别的操作策略完全不同。",
     "aliases": ["分析级别", "时间级别"]},

    # ===== 结构元素 =====
    {"id": "分型", "category": "结构元素", "importance": 22,
     "description": "缠论最小的结构单元。顶分型：三根K线中间最高，两侧较低。底分型：三根K线中间最低，两侧较高。分型是笔的定义基础，是走势的最小识别单元。",
     "aliases": ["顶分型", "底分型"]},
    {"id": "笔", "category": "结构元素", "importance": 24,
     "description": "由顶分型和底分型连接而成的最小走势单元，中间有足够数量的K线间隔。笔是线段的构成元素，是原始数据到缠论结构的基础桥梁，为识别次级别走势类型提供辅助。",
     "aliases": ["走势笔"]},
    {"id": "线段", "category": "结构元素", "importance": 26,
     "description": "由连续笔构成的更大结构，近似于次级别走势类型。线段是连接笔和走势类型的桥梁，是现代缠论中辅助识别次级别的重要工具。注意：线段是工具，次级别走势类型才是核心概念。",
     "aliases": ["走势线段"]},
    {"id": "连接段", "category": "结构元素", "importance": 24,
     "description": "趋势中连接两个同级别中枢的走势段，必然是次级别以下级别的走势类型。连接段级别越低，趋势越强；缺口连接是最强趋势的体现。",
     "aliases": []},
    {"id": "进入段", "category": "结构元素", "importance": 20,
     "description": "走势类型的起始段，进入中枢前的走势。进入段确定走势类型的开始，与中枢共同构成完整的走势结构。",
     "aliases": []},
    {"id": "离开段", "category": "结构元素", "importance": 22,
     "description": "在盘整中，离开中枢的走势类型，必然是次级别以下级别。离开段是测试中枢的重要信号，其级别和力度决定盘整的演化方向（继续震荡还是突破）。",
     "aliases": []},

    # ===== 走势类型 =====
    {"id": "趋势", "category": "走势类型", "importance": 32,
     "description": "某级别走势类型中包含两个或以上依次同向中枢。分为上涨趋势和下跌趋势。趋势由中枢+连接段+中枢构成，趋势有明确的延续性。趋势的判断依赖于中枢的同向性和不重叠性。",
     "aliases": ["趋势走势"]},
    {"id": "盘整", "category": "走势类型", "importance": 30,
     "description": "某级别走势类型中只包含一个中枢。盘整方向不明确，随时可能向上或向下突破。操作策略：在中枢下沿买入、上沿卖出做震荡，或等待第三类买卖点确认后入场。",
     "aliases": ["震荡"]},
    {"id": "上涨趋势", "category": "走势类型", "importance": 24,
     "description": "包含两个以上依次向上的同向中枢的走势，连接段在上涨方向。上涨趋势中有明确的第一、二、三类买点机会，以及趋势背驰后的卖出机会。",
     "aliases": []},
    {"id": "下跌趋势", "category": "走势类型", "importance": 24,
     "description": "包含两个以上依次向下的同向中枢的走势，连接段在下跌方向。下跌趋势中有明确的第一、二、三类卖点机会，以及趋势背驰后的买入机会。",
     "aliases": []},
    {"id": "中枢震荡", "category": "走势类型", "importance": 20,
     "description": "价格在中枢区间内反复震荡的走势形态。对中枢震荡不必过分关心，但要注意次级盘整背驰信号，以及中枢的形成、延伸和破坏节点。",
     "aliases": []},
    {"id": "中枢扩展", "category": "走势类型", "importance": 20,
     "description": "当走势在中枢区间外运动后返回并超出原中枢范围时，形成更大级别的中枢。中枢扩展是背驰后的三种转折方式之一，意味着级别提升而非趋势反转。",
     "aliases": ["级别扩展"]},

    # ===== 买卖点 =====
    {"id": "第一类买点", "category": "买卖点", "importance": 30,
     "description": "下跌趋势背驰后形成的买入点，位于趋势的最低点附近。判断：最后一段下跌出现背驰（MACD面积缩小），用次级别精确确认。第一类买点最安全但最难识别，需要丰富的背驰判断经验。",
     "aliases": ["一买"]},
    {"id": "第二类买点", "category": "买卖点", "importance": 28,
     "description": "第一类买点后第一次上涨并回抽时形成的买点。位于第一次上涨后的回调，通常在前中枢附近。判断：次级别背驰确认。比第一类买点更容易识别，成功率较高。",
     "aliases": ["二买"]},
    {"id": "第三类买点", "category": "买卖点", "importance": 28,
     "description": "中枢向上突破后的第一次回抽确认点（不回到中枢上沿ZG）。由中枢定理三推导。判断：次级别离开段+次级别回抽段均完整，且回抽不破中枢上沿ZG。适合追涨，确认趋势延续。",
     "aliases": ["三买"]},
    {"id": "第一类卖点", "category": "买卖点", "importance": 30,
     "description": "上涨趋势背驰后形成的卖出点，位于趋势的最高点附近。判断：最后一段上涨出现背驰（MACD红柱缩短、黄白线不创新高）。第一类卖点最关键但最难识别。",
     "aliases": ["一卖"]},
    {"id": "第二类卖点", "category": "买卖点", "importance": 28,
     "description": "第一类卖点后第一次下跌并反弹时形成的卖点。位于第一次下跌后的反弹，通常在前中枢附近。判断：次级别背驰确认。比第一类卖点更容易识别。",
     "aliases": ["二卖"]},
    {"id": "第三类卖点", "category": "买卖点", "importance": 28,
     "description": "中枢向下跌破后的第一次反弹确认点（不回到中枢下沿ZD）。由中枢定理三推导。判断：次级别离开段+次级别回抽段均完整，且反弹不破中枢下沿ZD。确认趋势转折，适合止损。",
     "aliases": ["三卖"]},
    {"id": "买卖点完备性", "category": "买卖点", "importance": 22,
     "description": "缠论三类买卖点是完备的，涵盖了所有可能的操作机会：趋势转折（第一类）、中枢形成后确认（第二类）、趋势延续确认（第三类）。不存在第四类买卖点。",
     "aliases": []},

    # ===== 定理系统 =====
    {"id": "中枢定理一", "category": "定理系统", "importance": 24,
     "description": "在趋势中，连接两个同级别中枢的必然是次级别以下级别的走势类型。连接段级别越低，趋势越强；缺口连接是最强趋势（最低级别的连接）。",
     "aliases": []},
    {"id": "中枢定理二", "category": "定理系统", "importance": 24,
     "description": "在盘整中，无论是离开还是返回中枢的走势类型必然是次级别以下的。离开/返回段是对中枢的测试，级别低于中枢才是真正的测试而非新的博弈。",
     "aliases": []},
    {"id": "中枢定理三", "category": "定理系统", "importance": 26,
     "description": "某级别中枢的破坏，当且仅当一个次级别走势离开该中枢后，其后的次级别回抽走势不重新回到该中枢内。中枢破坏直接导致第三类买卖点。",
     "aliases": []},
    {"id": "背驰买卖点定理", "category": "定理系统", "importance": 24,
     "description": "任一背驰都必然制造某级别的买卖点，任一级别的买卖点都必然源自某级别走势的背驰。背驰和买卖点一一对应，互为充要条件。",
     "aliases": []},
    {"id": "转折定理", "category": "定理系统", "importance": 26,
     "description": "某级别趋势的背驰将导致：(1)该趋势最后一个中枢的级别扩展，(2)该级别更大级别的盘整，或(3)该级别以上级别的反趋势。三种情况都可能，需观察次级别演化来判断。",
     "aliases": []},
    {"id": "小背驰大转折", "category": "定理系统", "importance": 22,
     "description": "小级别顶背驰引发大级别向下的必要条件是该级别走势的最后一个次级别中枢出现第三类卖点；底背驰引发大级别向上同理。小转大的关键是次级别中枢破坏。",
     "aliases": ["小转大"]},
    {"id": "走势分解定理一", "category": "定理系统", "importance": 20,
     "description": "任何走势都可以被分解为上涨、下跌、盘整的连接。走势分解具有唯一性，这是'不预测只应对'的数学基础。",
     "aliases": []},
    {"id": "走势分解定理二", "category": "定理系统", "importance": 20,
     "description": "任何走势类型至少由三段以上次级别走势构成。中枢由三段次级别重叠，趋势由中枢+连接段+中枢构成，保证了走势类型的最小完整性。",
     "aliases": []},

    # ===== 操作方法 =====
    {"id": "区间套", "category": "操作方法", "importance": 28,
     "description": "精确定位买卖点的方法：在高级别找到背驰段，切换到次级别找该段的背驰段，继续降级，直到精确定位买卖点。每降一级，精度提高一次。区间套体现了自同构性定理的实战应用。",
     "aliases": []},
    {"id": "多级别联立", "category": "操作方法", "importance": 28,
     "description": "三维操作框架：大级别（日线/周线）确定方向，中级别（30分/60分）确定结构，小级别（5分/1分）精确操作。三个级别联立分析，提高操作成功率和精确度。",
     "aliases": ["多级别分析"]},
    {"id": "同级别分解", "category": "操作方法", "importance": 22,
     "description": "将走势按照同一级别标准分解的方法，确保分解的唯一性和客观性。避免主观判断导致的分析偏差，是走势必完美定理的直接应用。",
     "aliases": []},
    {"id": "不预测只应对", "category": "操作方法", "importance": 24,
     "description": "缠论的核心操作哲学。对当下走势进行完全分类，针对每种可能的走势演化制定应对策略，根据走势实际演化动态调整操作，而非试图预测未来走势。",
     "aliases": ["应对而非预测"]},
    {"id": "中枢震荡操作", "category": "操作方法", "importance": 20,
     "description": "在盘整中，利用中枢上沿卖出、中枢下沿买入进行短差操作的方法。需要确认离开/返回段是次级别以下，否则说明中枢已经扩展。",
     "aliases": []},
    {"id": "趋势跟踪操作", "category": "操作方法", "importance": 22,
     "description": "在趋势中，顺趋势方向操作，在第二、三类买卖点入场，持有到趋势背驰后退出。结合多级别联立分析，提高趋势判断的准确性。",
     "aliases": []},

    # ===== 风险管理 =====
    {"id": "止损", "category": "风险管理", "importance": 22,
     "description": "基于次级别结构设置止损：第一类买点止损在次级别走势低点，第二类买点止损在次级别中枢下沿，第三类买点止损在次级别回抽低点。次级别结构是精确止损的依据。",
     "aliases": []},
    {"id": "仓位管理", "category": "风险管理", "importance": 20,
     "description": "根据次级别与高级别的一致性决定仓位：次级别结构清晰、与高级别方向一致→大仓位；次级别结构模糊、与高级别方向不一致→小仓位。",
     "aliases": []},
    {"id": "止盈", "category": "风险管理", "importance": 20,
     "description": "基于次级别信号动态止盈：次级别背驰→部分止盈；次级别中枢破坏→全部止盈。目标位通常是下一个次级别中枢位置或前期高低点。",
     "aliases": []},

    # ===== 级别体系 =====
    {"id": "1分钟级别", "category": "级别体系", "importance": 16,
     "description": "最小常用操作级别，用于精确入场出场。在区间套中作为最精细的定位工具。",
     "aliases": ["1分"]},
    {"id": "5分钟级别", "category": "级别体系", "importance": 18,
     "description": "常用于日内精确操作的次级别。30分钟操作时，5分钟是其次级别。用于精确识别背驰、定位买卖点。",
     "aliases": ["5分"]},
    {"id": "30分钟级别", "category": "级别体系", "importance": 20,
     "description": "短线操作的主要级别，中级结构分析的核心工具。日线操作时，30分钟是其次级别。",
     "aliases": ["30分"]},
    {"id": "日线级别", "category": "级别体系", "importance": 22,
     "description": "中期操作和趋势分析的核心级别，确定中期操作方向。对大多数投资者是重要的参考级别。",
     "aliases": ["日线"]},
    {"id": "周线级别", "category": "级别体系", "importance": 20,
     "description": "长期趋势分析的核心级别，确定大方向。在多级别联立中通常作为最高参考级别。",
     "aliases": ["周线"]},

    # ===== 哲学思想 =====
    {"id": "当下为锚", "category": "哲学思想", "importance": 22,
     "description": "缠论操作哲学：操作只能在当下执行，以当下为锚点，但当下不是孤立的。当下是连接过去走势和未来可能的节点，全局提供操作依据，当下是执行时点。",
     "aliases": []},
    {"id": "全局为依", "category": "哲学思想", "importance": 22,
     "description": "缠论操作哲学：全局包括过去走势演化、当前状态、未来可能演化路径。没有全局观，操作是盲目的。全局是判断结构完整性、识别背驰、制定应对策略的依据。",
     "aliases": []},
    {"id": "能量层次", "category": "哲学思想", "importance": 20,
     "description": "市场的物理学理解：次级别能量积累→高级别能量爆发，高级别能量变化必然先在次级别体现。能量守恒在不同级别间转化，背驰是能量耗尽的标志。",
     "aliases": []},
    {"id": "博弈均衡", "category": "哲学思想", "importance": 20,
     "description": "中枢的博弈论本质：中枢是多空双方的纳什均衡，三段次级别博弈的综合均衡形成高级别中枢。中枢破坏=均衡打破=第三类买卖点。博弈传递从次级别到高级别。",
     "aliases": ["纳什均衡"]},
    {"id": "递归自组织", "category": "哲学思想", "importance": 18,
     "description": "走势的数学本质：Level(n) = f(Level(n-1))，高级别走势由次级别递归生成。次级别走势互动自发形成高级别中枢（自组织），走势从简单到复杂的涌现。",
     "aliases": []},

    # ===== 三维统一（来自三维统一文档） =====
    {"id": "缠论视角", "category": "三维统一", "importance": 26,
     "description": "三维统一中的观测工具：识别市场结构。核心概念包括中枢（价格震荡的核心区域）、趋势（价格离开中枢的单向运动）、背驰（动能衰减的转折信号）、买卖点（结构转折的关键位置）。",
     "aliases": ["结构分析"]},
    {"id": "博弈论视角", "category": "三维统一", "importance": 26,
     "description": "三维统一中的分析框架：理解市场博弈。参与者包括多头和空头，策略对应买卖点，均衡对应中枢。中枢是多空博弈的纳什均衡点，中枢破坏意味着博弈均衡的打破。",
     "aliases": ["博弈分析"]},
    {"id": "量子力学视角", "category": "三维统一", "importance": 26,
     "description": "三维统一中的深度理解：类比市场量子态。波函数对应走势可能性，坍缩对应买卖点确认，跃迁对应中枢突破。观察者效应说明分析本身影响市场。",
     "aliases": ["量子类比"]},
    {"id": "波函数坍缩", "category": "三维统一", "importance": 18,
     "description": "量子力学视角下的买卖点类比：走势在背驰前处于叠加态（上涨/下跌概率叠加），买卖点确认的瞬间就是波函数坍缩——不确定性变为确定性。",
     "aliases": []},
    {"id": "量子跃迁", "category": "三维统一", "importance": 18,
     "description": "量子力学视角下的中枢突破类比：价格从中枢束缚态跃迁到自由态。中枢就像量子势阱，价格被困在其中；第三类买卖点就是量子跃迁的条件。",
     "aliases": []},
]

RELATIONS = [
    # 基础原理
    {"source": "走势终完美", "target": "走势必完美", "label": "操作化", "weight": 3},
    {"source": "走势终完美", "target": "完全分类", "label": "基础", "weight": 2},
    {"source": "走势终完美", "target": "中枢", "label": "包含", "weight": 3},
    {"source": "自同构性", "target": "级别", "label": "决定", "weight": 2},
    {"source": "自同构性", "target": "区间套", "label": "理论基础", "weight": 2},
    {"source": "走势必完美", "target": "走势分解定理一", "label": "推导", "weight": 2},
    {"source": "走势必完美", "target": "走势分解定理二", "label": "推导", "weight": 2},
    {"source": "走势必完美", "target": "同级别分解", "label": "应用", "weight": 2},

    # 核心概念
    {"source": "次级别", "target": "中枢", "label": "构成", "weight": 4},
    {"source": "中枢", "target": "走势类型", "label": "构成", "weight": 3},
    {"source": "中枢", "target": "趋势", "label": "同向多枢", "weight": 3},
    {"source": "中枢", "target": "盘整", "label": "单枢", "weight": 3},
    {"source": "背驰", "target": "第一类买点", "label": "产生", "weight": 3},
    {"source": "背驰", "target": "第一类卖点", "label": "产生", "weight": 3},
    {"source": "背驰", "target": "转折定理", "label": "触发", "weight": 3},
    {"source": "级别", "target": "次级别", "label": "相邻级别", "weight": 3},
    {"source": "次级别", "target": "背驰", "label": "确认工具", "weight": 2},

    # 结构元素
    {"source": "分型", "target": "笔", "label": "构成", "weight": 2},
    {"source": "笔", "target": "线段", "label": "构成", "weight": 2},
    {"source": "线段", "target": "次级别", "label": "近似工具", "weight": 2},
    {"source": "连接段", "target": "趋势", "label": "连接中枢", "weight": 2},
    {"source": "离开段", "target": "中枢", "label": "测试", "weight": 2},
    {"source": "离开段", "target": "第三类买点", "label": "构成条件", "weight": 2},
    {"source": "离开段", "target": "第三类卖点", "label": "构成条件", "weight": 2},

    # 走势类型
    {"source": "趋势", "target": "上涨趋势", "label": "分类", "weight": 1},
    {"source": "趋势", "target": "下跌趋势", "label": "分类", "weight": 1},
    {"source": "盘整", "target": "中枢震荡", "label": "包含", "weight": 1},
    {"source": "盘整", "target": "中枢扩展", "label": "可能演化", "weight": 1},
    {"source": "走势类型", "target": "趋势", "label": "包含", "weight": 2},
    {"source": "走势类型", "target": "盘整", "label": "包含", "weight": 2},

    # 买卖点
    {"source": "第一类买点", "target": "第二类买点", "label": "确认", "weight": 2},
    {"source": "第二类买点", "target": "第三类买点", "label": "延续", "weight": 1},
    {"source": "第一类卖点", "target": "第二类卖点", "label": "确认", "weight": 2},
    {"source": "第二类卖点", "target": "第三类卖点", "label": "延续", "weight": 1},
    {"source": "中枢定理三", "target": "第三类买点", "label": "推导", "weight": 2},
    {"source": "中枢定理三", "target": "第三类卖点", "label": "推导", "weight": 2},
    {"source": "买卖点完备性", "target": "第一类买点", "label": "包含", "weight": 1},
    {"source": "买卖点完备性", "target": "第二类买点", "label": "包含", "weight": 1},
    {"source": "买卖点完备性", "target": "第三类买点", "label": "包含", "weight": 1},

    # 定理
    {"source": "中枢定理一", "target": "趋势", "label": "约束", "weight": 2},
    {"source": "中枢定理二", "target": "盘整", "label": "约束", "weight": 2},
    {"source": "中枢定理三", "target": "中枢", "label": "破坏条件", "weight": 3},
    {"source": "背驰买卖点定理", "target": "背驰", "label": "定义关系", "weight": 2},
    {"source": "转折定理", "target": "中枢扩展", "label": "三种情况", "weight": 1},
    {"source": "转折定理", "target": "背驰", "label": "基于", "weight": 2},
    {"source": "小背驰大转折", "target": "次级别", "label": "依赖", "weight": 2},
    {"source": "小背驰大转折", "target": "第三类买点", "label": "必要条件", "weight": 2},
    {"source": "小背驰大转折", "target": "第三类卖点", "label": "必要条件", "weight": 2},
    {"source": "走势分解定理一", "target": "完全分类", "label": "支撑", "weight": 2},
    {"source": "走势分解定理二", "target": "次级别", "label": "确认地位", "weight": 2},

    # 操作方法
    {"source": "区间套", "target": "多级别联立", "label": "组合", "weight": 2},
    {"source": "多级别联立", "target": "不预测只应对", "label": "方法论", "weight": 2},
    {"source": "不预测只应对", "target": "完全分类", "label": "体现", "weight": 2},
    {"source": "中枢震荡操作", "target": "盘整", "label": "应用场景", "weight": 2},
    {"source": "趋势跟踪操作", "target": "趋势", "label": "应用场景", "weight": 2},
    {"source": "区间套", "target": "次级别", "label": "逐级降低", "weight": 2},
    {"source": "多级别联立", "target": "级别", "label": "核心要素", "weight": 2},

    # 风险管理
    {"source": "止损", "target": "次级别", "label": "依据", "weight": 2},
    {"source": "仓位管理", "target": "次级别", "label": "依据", "weight": 2},
    {"source": "止盈", "target": "背驰", "label": "触发信号", "weight": 2},
    {"source": "止盈", "target": "中枢定理三", "label": "退出依据", "weight": 1},

    # 级别体系
    {"source": "1分钟级别", "target": "5分钟级别", "label": "次级别", "weight": 1},
    {"source": "5分钟级别", "target": "30分钟级别", "label": "次级别", "weight": 1},
    {"source": "30分钟级别", "target": "日线级别", "label": "次级别", "weight": 1},
    {"source": "日线级别", "target": "周线级别", "label": "次级别", "weight": 1},

    # 哲学思想
    {"source": "当下为锚", "target": "全局为依", "label": "统一", "weight": 3},
    {"source": "当下为锚", "target": "不预测只应对", "label": "体现", "weight": 2},
    {"source": "全局为依", "target": "多级别联立", "label": "体现", "weight": 2},
    {"source": "能量层次", "target": "次级别", "label": "物理本质", "weight": 2},
    {"source": "能量层次", "target": "背驰", "label": "能量耗尽", "weight": 2},
    {"source": "博弈均衡", "target": "中枢", "label": "本质解释", "weight": 2},
    {"source": "博弈均衡", "target": "中枢定理三", "label": "博弈打破", "weight": 2},
    {"source": "递归自组织", "target": "走势必完美", "label": "数学本质", "weight": 2},
    {"source": "递归自组织", "target": "自同构性", "label": "机制", "weight": 2},

    # 三维统一
    {"source": "缠论视角", "target": "中枢", "label": "识别", "weight": 2},
    {"source": "缠论视角", "target": "背驰", "label": "识别", "weight": 2},
    {"source": "缠论视角", "target": "走势类型", "label": "分析", "weight": 2},
    {"source": "博弈论视角", "target": "博弈均衡", "label": "理论对应", "weight": 2},
    {"source": "博弈论视角", "target": "中枢", "label": "均衡解释", "weight": 2},
    {"source": "量子力学视角", "target": "波函数坍缩", "label": "包含", "weight": 1},
    {"source": "量子力学视角", "target": "量子跃迁", "label": "包含", "weight": 1},
    {"source": "波函数坍缩", "target": "买卖点完备性", "label": "类比", "weight": 1},
    {"source": "量子跃迁", "target": "第三类买点", "label": "类比", "weight": 1},
    {"source": "量子跃迁", "target": "第三类卖点", "label": "类比", "weight": 1},
]
